"use client";

import { useState } from "react";
import { CircleDollarSign, Download, FileSpreadsheet, Landmark, PiggyBank, ShieldCheck, Target, TrendingUp } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { getFinancialAnalytics } from "@/lib/finance/analytics";
import type { FinanceData } from "@/lib/finance/types";
import { formatCurrency, formatMonth, formatPercent } from "@/lib/formatters";
import { CurrencyValue, EmptyState, PanelHeader, ProgressBar, SectionHeader, StatusBadge } from "@/components/shared";

type Analytics = ReturnType<typeof getFinancialAnalytics>;

export function ReportView({ data, analytics, selectedMonth, setSelectedMonth, hidden, initialNote, onSaveNote, onPrint, onExcel }: {
  data: FinanceData;
  analytics: Analytics;
  selectedMonth: string;
  setSelectedMonth: (value:string)=>void;
  hidden: boolean;
  initialNote: string;
  onSaveNote: (note:string)=>void;
  onPrint: ()=>void;
  onExcel: ()=>void;
}) {
  const [note,setNote]=useState(initialNote);
  const expenseDelta = analytics.previous.expenses ? (analytics.totals.expenses-analytics.previous.expenses)/analytics.previous.expenses*100 : null;
  const incomeDelta = analytics.previous.income ? (analytics.totals.income-analytics.previous.income)/analytics.previous.income*100 : null;
  const recommendations = [
    analytics.totals.savingsRate < 10 ? "Considere definir um aporte logo após o recebimento para elevar a taxa de poupança." : "A taxa de poupança registrada é positiva; mantenha consistência e vincule o saldo às metas prioritárias.",
    analytics.reserveTarget && analytics.emergencyReserve < analytics.reserveTarget ? `A reserva cobre ${analytics.reserveMonths.toFixed(1)} meses; o marco interno do relatório é seis meses de gastos fixos.` : "A reserva registrada cobre o marco interno de seis meses dos gastos fixos deste período.",
    analytics.budgetTotal && analytics.totals.expenses > analytics.budgetTotal ? "O realizado superou o orçamento; revise as categorias acima de 100% antes do próximo fechamento." : "O orçamento está dentro do limite total registrado ou ainda não possui base completa.",
  ];
  return <section className="report-page section-page"><SectionHeader eyebrow="RELATÓRIO MENSAL" title={`Fechamento de ${formatMonth(selectedMonth)}`} description="Relatório executivo preparado para revisão, Excel e impressão em PDF." actions={<><label className="month-control"><span>Período</span><input type="month" value={selectedMonth} onChange={(event)=>setSelectedMonth(event.target.value)}/></label><button className="secondary-button" onClick={onExcel}><FileSpreadsheet size={16}/>Baixar Excel</button><button className="primary-button" onClick={onPrint}><Download size={16}/>Gerar PDF</button></>} />
    <article className="report-sheet">
      <header className="report-cover"><div><span className="report-logo"><CircleDollarSign/></span><span><small>NEXO FINANÇAS PESSOAIS</small><strong>Relatório mensal</strong><em>by Anderson de Araujo</em></span></div><div><small>PERÍODO</small><strong>{formatMonth(selectedMonth)}</strong><span>Gerado em {new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date())}</span></div></header>
      <section className="report-executive"><span>RESUMO EXECUTIVO</span><h2>{analytics.totals.count ? analytics.totals.balance>=0?"O período gerou caixa positivo com base nos registros.":"As despesas superaram as receitas registradas no período.":"O fechamento ainda não possui lançamentos."}</h2><p>{analytics.totals.count?<>Foram consolidados {analytics.totals.count} lançamentos, com entradas de <CurrencyValue value={analytics.totals.income} hidden={hidden}/>, saídas de <CurrencyValue value={analytics.totals.expenses} hidden={hidden}/> e saldo de <CurrencyValue value={analytics.totals.balance} hidden={hidden}/>.</>:"Cadastre movimentações ou selecione outro mês para formar o relatório sem dados fictícios."}</p></section>
      <section className="report-kpis"><div><span>Entradas</span><strong><CurrencyValue value={analytics.totals.income} hidden={hidden}/></strong><small>{incomeDelta===null?'Sem base anterior':`${incomeDelta>=0?'+':''}${formatPercent(incomeDelta)} vs. mês anterior`}</small></div><div><span>Saídas</span><strong><CurrencyValue value={analytics.totals.expenses} hidden={hidden}/></strong><small>{expenseDelta===null?'Sem base anterior':`${expenseDelta>=0?'+':''}${formatPercent(expenseDelta)} vs. mês anterior`}</small></div><div><span>Saldo</span><strong><CurrencyValue value={analytics.totals.balance} hidden={hidden}/></strong><small>Resultado do período</small></div><div><span>Taxa de poupança</span><strong>{formatPercent(analytics.totals.savingsRate)}</strong><small>da renda registrada</small></div></section>
      <section className="report-comparison"><PanelHeader eyebrow="COMPARAÇÃO" title="Mês atual × mês anterior"/><div><span><small>Indicador</small><strong>Atual</strong><strong>Anterior</strong></span><span><small>Receita</small><b><CurrencyValue value={analytics.totals.income} hidden={hidden}/></b><b><CurrencyValue value={analytics.previous.income} hidden={hidden}/></b></span><span><small>Despesa</small><b><CurrencyValue value={analytics.totals.expenses} hidden={hidden}/></b><b><CurrencyValue value={analytics.previous.expenses} hidden={hidden}/></b></span><span><small>Saldo</small><b><CurrencyValue value={analytics.totals.balance} hidden={hidden}/></b><b><CurrencyValue value={analytics.previous.balance} hidden={hidden}/></b></span><span><small>Poupança</small><b>{formatPercent(analytics.totals.savingsRate)}</b><b>{formatPercent(analytics.previous.savingsRate)}</b></span></div></section>
      <section className="report-main-grid"><article><PanelHeader eyebrow="EVOLUÇÃO" title="Entradas × saídas em 12 meses"/>{analytics.monthlyTrend.some((item)=>item.entradas||item.saidas)?<div className="chart chart-large"><ResponsiveContainer width="100%" height="100%"><AreaChart data={analytics.monthlyTrend}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={(value)=>`${value/1000}k`}/><Tooltip formatter={(value)=>hidden?'R$ ••••••':formatCurrency(Number(value))}/><Area dataKey="entradas" name="Entradas" stroke="#1f6b52" fill="#dcebe4" strokeWidth={2.5}/><Area dataKey="saidas" name="Saídas" stroke="#b75f51" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div>:<EmptyState compact title="Evolução em formação" description="O gráfico será criado com os meses que tiverem dados."/>}</article><article><PanelHeader eyebrow="DESPESAS" title="Categorias principais"/>{analytics.categories.length?<div className="report-ranking">{analytics.categories.slice(0,6).map((item,index)=><div key={item.name}><b>{index+1}</b><span><strong>{item.name}</strong><small>{formatPercent(item.percent)} das despesas</small></span><CurrencyValue value={item.value} hidden={hidden}/></div>)}</div>:<EmptyState compact title="Sem despesas" description="Nenhuma saída registrada neste mês."/>}</article></section>
      <section className="report-secondary-grid"><article><PanelHeader eyebrow="ORÇADO × REALIZADO" title="Planejamento por categoria"/>{analytics.budgetByCategory.length?<div className="report-budget">{analytics.budgetByCategory.slice(0,8).map((item)=><div key={item.id}><span><strong>{item.category}</strong><small><CurrencyValue value={item.actual} hidden={hidden}/> / <CurrencyValue value={item.amount} hidden={hidden}/></small></span><ProgressBar value={item.usedPct} tone={item.usedPct>100?'negative':item.usedPct>=80?'attention':'positive'}/><StatusBadge tone={item.usedPct>100?'negative':item.usedPct>=80?'attention':'positive'}>{formatPercent(item.usedPct)}</StatusBadge></div>)}</div>:<EmptyState compact title="Sem orçamento" description="Não há valores planejados para o período."/>}</article><article><PanelHeader eyebrow="POSIÇÃO FINANCEIRA" title="Patrimônio e investimentos"/><dl className="report-position"><div><dt><Landmark/>Patrimônio líquido</dt><dd><CurrencyValue value={analytics.netWorth} hidden={hidden}/></dd></div><div><dt><TrendingUp/>Investimentos</dt><dd><CurrencyValue value={analytics.portfolioTotal} hidden={hidden}/></dd></div><div><dt><ShieldCheck/>Reserva</dt><dd><CurrencyValue value={analytics.emergencyReserve} hidden={hidden}/></dd></div><div><dt><PiggyBank/>Dívidas</dt><dd><CurrencyValue value={analytics.liabilities} hidden={hidden}/></dd></div></dl></article></section>
      <section className="report-goals-alerts"><article><PanelHeader eyebrow="METAS" title="Progresso dos objetivos"/>{data.goals.length?<div>{data.goals.slice(0,5).map((goal)=><span key={goal.id}><strong>{goal.name}</strong><ProgressBar value={goal.target?goal.current/goal.target*100:0}/><small><CurrencyValue value={goal.current} hidden={hidden}/> de <CurrencyValue value={goal.target} hidden={hidden}/></small></span>)}</div>:<EmptyState compact title="Sem metas" description="Nenhum objetivo financeiro cadastrado." icon={Target}/>}</article><article><PanelHeader eyebrow="ALERTAS" title="Pontos do fechamento"/>{analytics.alerts.length?<div className="report-alerts">{analytics.alerts.map((alert)=><p key={alert.title}><StatusBadge tone={alert.level==='important'?'negative':alert.level==='attention'?'attention':'info'}>{alert.level==='important'?'Importante':alert.level==='attention'?'Atenção':'Informação'}</StatusBadge><strong>{alert.title}</strong><span>{alert.text}</span></p>)}</div>:<p className="report-no-alerts"><ShieldCheck/>Nenhum alerta contextual para os dados disponíveis.</p>}</article></section>
      <section className="report-recommendations"><div><span>RECOMENDAÇÕES AUTOMÁTICAS</span><h2>Próximos pontos de revisão</h2></div><ol>{recommendations.map((item)=><li key={item}>{item}</li>)}</ol></section>
      <section className="report-notes"><span>OBSERVAÇÕES DO MÊS</span><textarea value={note} onChange={(event)=>setNote(event.target.value)} placeholder="Registre decisões, imprevistos, aprendizados e ajustes para o próximo mês."/><button className="secondary-button" onClick={()=>onSaveNote(note)}>Salvar observações</button></section>
      <footer className="report-footer"><span>NEXO FINANÇAS PESSOAIS · by Anderson de Araujo</span><span>{formatMonth(selectedMonth)} · uso pessoal</span></footer>
    </article>
  </section>;
}
